### ISSUE TITLE
点击虚拟键盘的删除键，控件中的数字被删除了两个

### ISSUE THREAD

**Issue by Janky-Young** [JackTuoTuo/VerificationCodeView#11]
点击删除时，VerificationCodeView.class中的BackSpaceListener和OnKeyListener的监听都执行了。（测试机：魅蓝6）

**Comment by z2700589** [comment]
同上

**Comment by zqr95518** [comment]
同上，华为M3平板

**Comment by JackTuoTuo** [comment]
已解决

**Comment by cloud-sunny** [comment]
我现在还有这个问题,小米手机

**Comment by ZhouBey** [comment]
oppo也有这个问题

**Comment by ZhouBey** [comment]
> 我现在还有这个问题,小米手机

你解决了吗

**Comment by JackTuoTuo** [comment]
用的是最新版本么&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhou Peiyuan"<notifications@github.com&gt;; 
发送时间: 2020年1月8日(星期三) 中午11:48
收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&gt;; 
抄送: "不忘初心"<839539179@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11)




oppo也有这个问题

**Comment by ZhouBey** [comment]
最新是1.0.5还是1.0.4



---原始邮件---
发件人: "JackTuoTuo"<notifications@github.com&gt;
发送时间: 2020年1月8日(周三) 中午11:49
收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&gt;;
抄送: "Zhou Peiyuan"<931371256@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11)


用的是最新版本么&amp;nbsp; 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Zhou Peiyuan"<notifications@github.com&amp;gt;;  
 发送时间: 2020年1月8日(星期三) 中午11:48 
 收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&amp;gt;;  
 抄送: "不忘初心"<839539179@qq.com&amp;gt;; "State change"<state_change@noreply.github.com&amp;gt;;  
 主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11) 
 
 
 
 
 oppo也有这个问题

**Comment by JackTuoTuo** [comment]
最新的是 1.0.5 多看下 readme 更新日志都有的 解决了哪些问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhou Peiyuan"<notifications@github.com&gt;; 
发送时间: 2020年1月8日(星期三) 中午11:51
收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&gt;; 
抄送: "不忘初心"<839539179@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11)



最新是1.0.5还是1.0.4 
 
 
 
 ---原始邮件--- 
 发件人: "JackTuoTuo"<notifications@github.com&amp;gt; 
 发送时间: 2020年1月8日(周三) 中午11:49 
 收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&amp;gt;; 
 抄送: "Zhou Peiyuan"<931371256@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11) 
 
 
 用的是最新版本么&amp;amp;nbsp;  
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: "Zhou Peiyuan"<notifications@github.com&amp;amp;gt;;   
  发送时间: 2020年1月8日(星期三) 中午11:48  
  收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&amp;amp;gt;;   
  抄送: "不忘初心"<839539179@qq.com&amp;amp;gt;; "State change"<state_change@noreply.github.com&amp;amp;gt;;   
  主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11)  
   
   
   
   
  oppo也有这个问题

**Comment by ZhouBey** [comment]
好的，谢谢



---原始邮件---
发件人: "JackTuoTuo"<notifications@github.com&gt;
发送时间: 2020年1月8日(周三) 中午11:53
收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&gt;;
抄送: "Zhou Peiyuan"<931371256@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11)


最新的是 1.0.5 多看下 readme 更新日志都有的 解决了哪些问题 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "Zhou Peiyuan"<notifications@github.com&amp;gt;;  
 发送时间: 2020年1月8日(星期三) 中午11:51 
 收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&amp;gt;;  
 抄送: "不忘初心"<839539179@qq.com&amp;gt;; "State change"<state_change@noreply.github.com&amp;gt;;  
 主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11) 
 
 
 
 最新是1.0.5还是1.0.4  
   
   
   
  ---原始邮件---  
  发件人: "JackTuoTuo"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年1月8日(周三) 中午11:49  
  收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&amp;amp;gt;;  
  抄送: "Zhou Peiyuan"<931371256@qq.com&amp;amp;gt;;"Comment"<comment@noreply.github.com&amp;amp;gt;;  
  主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11)  
   
   
  用的是最新版本么&amp;amp;amp;nbsp;   
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: "Zhou Peiyuan"<notifications@github.com&amp;amp;amp;gt;;    
   发送时间: 2020年1月8日(星期三) 中午11:48   
   收件人: "JackTuoTuo/VerificationCodeView"<VerificationCodeView@noreply.github.com&amp;amp;amp;gt;;    
   抄送: "不忘初心"<839539179@qq.com&amp;amp;amp;gt;; "State change"<state_change@noreply.github.com&amp;amp;amp;gt;;    
   主题: Re: [JackTuoTuo/VerificationCodeView] 点击虚拟键盘的删除键，控件中的数字被删除了两个 (#11)   
     
     
     
     
   oppo也有这个问题
