### ISSUE TITLE
在activity里设置输入框数量怎么实现

### ISSUE THREAD

**Issue by mycold** [JackTuoTuo/VerificationCodeView#2]
![image](https://user-images.githubusercontent.com/14937950/33163780-fa3e8ab8-d06a-11e7-804f-df3fa7092254.png)
我直接这样设置在外面调用没效果

**Comment by JackTuoTuo** [comment]
最近将会调整代码 实现这个功能。有问题加我 qq 839539179

**Comment by JackTuoTuo** [comment]
已阅读readme
