### ISSUE TITLE
删除键监听没有效果

### ISSUE THREAD

**Issue by happinesspeople** [JackTuoTuo/VerificationCodeView#3]
在输入到一半的时候，点击系统软键盘的删除按钮，没有任何反应，日志打印结果发现
     // 监听删除按键
        et.setOnKeyListener(new OnKeyListener() {
            @Override
            public boolean onKey(View v, int keyCode, KeyEvent event) {
                Log.i("ceshi","onKey1") ;
                if (keyCode == KeyEvent.KEYCODE_DEL && event.getAction() == KeyEvent.ACTION_DOWN) {
                    onKeyDelete();
                    Log.i("ceshi","onKey2") ;
                    return true;
                }
                return false;
            }
        });
并没有经过这个回调，这是什么原因呢？

**Comment by JackTuoTuo** [comment]
这个方法监听的是物理键盘，可能监听不到软键盘。我最近在优化这个项目，有问题可以加我qq 839539179

**Comment by JackTuoTuo** [comment]
该bug已在 1.0.4 版本解决
