### ISSUE TITLE
请问一下如何能主动获取焦点弹出输入框

### ISSUE THREAD

**Issue by wangqi0** [JackTuoTuo/VerificationCodeView#4]
et = (EditText) this.findViewById(R.id.et);
 et.requestFocus();

我在et后面加上这句代码也获取不了焦点，必须用户手动点击才可以弹出输入框。
请问一下如何能主动获取它的焦点弹出输入框呢？

**Comment by JackTuoTuo** [comment]
有方法返回了 et 你可以使用它 获取焦点
