### ISSUE TITLE
如何将该控件作为密码输入框使用？

### ISSUE THREAD

**Issue by koala0x** [JackTuoTuo/VerificationCodeView#5]
`    

    // 给TextView 设置文字
    private void setText(String inputContent) {
        for (int i = 0; i < mTextViews.length; i++) {
            TextView tv = mTextViews[i];
            if (tv.getText().toString().trim().equals("")) {
                tv.setText(inputContent);
                tv.setTransformationMethod(PasswordTransformationMethod.getInstance()); // 改变TextView属性为展示密文的属性
                // 添加输入完成的监听
                if (inputCompleteListener != null) {
                    inputCompleteListener.inputComplete();
                }
                tv.setBackgroundDrawable(mEtBackgroundDrawableNormal);
                if (i < mEtNumber - 1) {
                    mTextViews[i + 1].setBackgroundDrawable(mEtBackgroundDrawableFocus);
                }
                break;
            }
        }
    }`

**Comment by JackTuoTuo** [comment]
请看 更新日志和 todo  这个功能 还没更新  最近太忙了  思路 大该 就是 输入一秒后 用 “*” 代替文字 你可以自己先修改  如果你写的很棒  可以合并到我的代码

**Comment by JackTuoTuo** [comment]
已解决
