### ISSUE TITLE
textSize单位问题

### ISSUE THREAD

**Issue by FCBXavi** [JackTuoTuo/VerificationCodeView#6]
在VerificationCodeView 77行获取TextSize时mEtTextSize = typedArray.getDimensionPixelSize(R.styleable.VerificationCodeView_icv_et_text_size, 16);获取到的size是以px为单位的，但是在136行textView.setTextSize(etTextSize);时，使用的依旧是同样的数字，这里TextView会把这个size当成是sp为单位进行设置，导致在xml文件中设置的sp为单位的字体被放大。

如果是有问题的话，应该有两个解决办法：
1.在获取到mEtTextSize后将其转换为sp 。
2.textView.setTextSize时使用textView.setTextSize(TypedValue.COMPLEX_UNIT_PX,mEtTextSize);
两者使用其一应该就可以解决

个人观点😄

**Comment by JackTuoTuo** [comment]
感谢提示  我明天看看

**Comment by JackTuoTuo** [comment]
已解决
